version: "3"
services:
  client:
    build:
      dockerfile: dockerfile
      context: ./client
    restart: unless-stopped
    ports:
      - 3000:3000
  server:
    build:
      dockerfile: dockerfile
      context: ./server
    restart: unless-stopped
    ports:
      - 5000:5000
