FROM node:18.13.0-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY tsconfig.json package.json yarn.lock .env /app/
COPY src /app/src/

RUN yarn --frozen-lockfile \
  && yarn build

ENV NODE_ENV production
ENV PORT 5000
EXPOSE 5000

USER node

CMD ["node", "dist/main.js"]